---
- name: "Launch an HCPSS Schoolsite"
  hosts: all

  vars:
    # acronyms:
    #   - fes
    #   - ahs
    # schoolsite_database_name: "{{ acronym }}"
    # schoolsite_database_username: "{{ acronym }}"
    # schoolsite_database_pass: "{{ acronym }}"
    # database_name: "{{ schoolsite_database_name }}"
    # database_user: "{{ schoolsite_database_username }}"
    # database_pass: "{{ schoolsite_database_pass }}"
    # schoolsite_acronym: "{{ acronym }}"
    # schoolsite_install_location: "/var/www/{{ schoolsite_acronym }}"
    # schoolsite_database_host: localhost
    # schoolsite_account_pass: admin

  roles:
    - geerlingguy.git
    - role: geerlingguy.php
      vars:
        php_memory_limit: "512M"
        php_date_timezone: "America/New_York"
        php_enable_php_fpm: true
        php_webserver_daemon: nginx
    - role: geerlingguy.php-mysql
      vars:
        php_mysql_package: php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - include_role:
        name: geerlingguy.mysql
      vars:
        mysql_databases:
          - name: "{{ acronym }}"
            collation: utf8_general_ci
            encoding: utf8
        mysql_users:
          - name: "{{ acronym }}"
            host: localhost
            password: "{{ acronym }}"
            priv: "*.*:ALL"
      loop: "{{ acronyms }}"
      loop_control:
        loop_var: acronym

    - include_role:
        name: geerlingguy.nginx
      vars:
        #nginx_vhost_template: "{{ playbook_dir }}/templates/school.hcpss.localhost.j2"
        nginx_vhosts:
          - server_name: "{{ acronym }}.hcpss.localhost"
            filename: "{{ acronym }}.hcpss.localhost.conf"
            template: "{{ playbook_dir }}/templates/school.hcpss.localhost.j2"
      loop: "{{ acronyms }}"
      loop_control:
        loop_var: acronym

    - include_tasks: schoolsite.yml
      with_items: "{{ acronyms }}"
      loop_control:
        loop_var: acronym
